// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0
/*
Agent Manifest Definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package manifests

import (
	"encoding/json"
)

// checks if the AgentlessConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentlessConfig{}

// AgentlessConfig Describes LLM configuration and prompts for agentless deployment
type AgentlessConfig struct {
	FrameworkType string `json:"framework_type"`
	// Specific model out of those configured to handle request used unless specified in request.
	DefaultModel string `json:"default_model"`
	// Mapping of available model names to settings.
	Models map[string]AgentlessModelSettings `json:"models"`
	// Default parameters for models specified in \"models\" property.
	DefaultModelParameters map[string]AgentlessModelParameters `json:"default_model_parameters,omitempty"`
	MessageTemplates       []AgentMessage                      `json:"message_templates,omitempty"`
}

// NewAgentlessConfig instantiates a new AgentlessConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentlessConfig(frameworkType string, defaultModel string, models map[string]AgentlessModelSettings) *AgentlessConfig {
	this := AgentlessConfig{}
	this.FrameworkType = frameworkType
	this.DefaultModel = defaultModel
	this.Models = models
	return &this
}

// NewAgentlessConfigWithDefaults instantiates a new AgentlessConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentlessConfigWithDefaults() *AgentlessConfig {
	this := AgentlessConfig{}
	return &this
}

// GetFrameworkType returns the FrameworkType field value
func (o *AgentlessConfig) GetFrameworkType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FrameworkType
}

// GetFrameworkTypeOk returns a tuple with the FrameworkType field value
// and a boolean to check if the value has been set.
func (o *AgentlessConfig) GetFrameworkTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FrameworkType, true
}

// SetFrameworkType sets field value
func (o *AgentlessConfig) SetFrameworkType(v string) {
	o.FrameworkType = v
}

// GetDefaultModel returns the DefaultModel field value
func (o *AgentlessConfig) GetDefaultModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultModel
}

// GetDefaultModelOk returns a tuple with the DefaultModel field value
// and a boolean to check if the value has been set.
func (o *AgentlessConfig) GetDefaultModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultModel, true
}

// SetDefaultModel sets field value
func (o *AgentlessConfig) SetDefaultModel(v string) {
	o.DefaultModel = v
}

// GetModels returns the Models field value
// If the value is explicit nil, the zero value for map[string]AgentlessModelSettings will be returned
func (o *AgentlessConfig) GetModels() map[string]AgentlessModelSettings {
	if o == nil {
		var ret map[string]AgentlessModelSettings
		return ret
	}

	return o.Models
}

// GetModelsOk returns a tuple with the Models field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentlessConfig) GetModelsOk() (*map[string]AgentlessModelSettings, bool) {
	if o == nil || IsNil(o.Models) {
		return nil, false
	}
	return &o.Models, true
}

// SetModels sets field value
func (o *AgentlessConfig) SetModels(v map[string]AgentlessModelSettings) {
	o.Models = v
}

// GetDefaultModelParameters returns the DefaultModelParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentlessConfig) GetDefaultModelParameters() map[string]AgentlessModelParameters {
	if o == nil {
		var ret map[string]AgentlessModelParameters
		return ret
	}
	return o.DefaultModelParameters
}

// GetDefaultModelParametersOk returns a tuple with the DefaultModelParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentlessConfig) GetDefaultModelParametersOk() (*map[string]AgentlessModelParameters, bool) {
	if o == nil || IsNil(o.DefaultModelParameters) {
		return nil, false
	}
	return &o.DefaultModelParameters, true
}

// HasDefaultModelParameters returns a boolean if a field has been set.
func (o *AgentlessConfig) HasDefaultModelParameters() bool {
	if o != nil && IsNil(o.DefaultModelParameters) {
		return true
	}

	return false
}

// SetDefaultModelParameters gets a reference to the given map[string]AgentlessModelParameters and assigns it to the DefaultModelParameters field.
func (o *AgentlessConfig) SetDefaultModelParameters(v map[string]AgentlessModelParameters) {
	o.DefaultModelParameters = v
}

// GetMessageTemplates returns the MessageTemplates field value if set, zero value otherwise.
func (o *AgentlessConfig) GetMessageTemplates() []AgentMessage {
	if o == nil || IsNil(o.MessageTemplates) {
		var ret []AgentMessage
		return ret
	}
	return o.MessageTemplates
}

// GetMessageTemplatesOk returns a tuple with the MessageTemplates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessConfig) GetMessageTemplatesOk() ([]AgentMessage, bool) {
	if o == nil || IsNil(o.MessageTemplates) {
		return nil, false
	}
	return o.MessageTemplates, true
}

// HasMessageTemplates returns a boolean if a field has been set.
func (o *AgentlessConfig) HasMessageTemplates() bool {
	if o != nil && !IsNil(o.MessageTemplates) {
		return true
	}

	return false
}

// SetMessageTemplates gets a reference to the given []AgentMessage and assigns it to the MessageTemplates field.
func (o *AgentlessConfig) SetMessageTemplates(v []AgentMessage) {
	o.MessageTemplates = v
}

func (o AgentlessConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentlessConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["framework_type"] = o.FrameworkType
	toSerialize["default_model"] = o.DefaultModel
	if o.Models != nil {
		toSerialize["models"] = o.Models
	}
	if o.DefaultModelParameters != nil {
		toSerialize["default_model_parameters"] = o.DefaultModelParameters
	}
	if !IsNil(o.MessageTemplates) {
		toSerialize["message_templates"] = o.MessageTemplates
	}
	return toSerialize, nil
}

type NullableAgentlessConfig struct {
	value *AgentlessConfig
	isSet bool
}

func (v NullableAgentlessConfig) Get() *AgentlessConfig {
	return v.value
}

func (v *NullableAgentlessConfig) Set(val *AgentlessConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentlessConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentlessConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentlessConfig(val *AgentlessConfig) *NullableAgentlessConfig {
	return &NullableAgentlessConfig{value: val, isSet: true}
}

func (v NullableAgentlessConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentlessConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
