// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0
/*
Agent Manifest Definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package manifests

import (
	"encoding/json"
)

// checks if the AgentMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentMessage{}

// AgentMessage Input message to LLM service
type AgentMessage struct {
	Role    *string `json:"role,omitempty"`
	Content string  `json:"content"`
}

// NewAgentMessage instantiates a new AgentMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentMessage(content string) *AgentMessage {
	this := AgentMessage{}
	var role string = "user"
	this.Role = &role
	this.Content = content
	return &this
}

// NewAgentMessageWithDefaults instantiates a new AgentMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentMessageWithDefaults() *AgentMessage {
	this := AgentMessage{}
	var role string = "user"
	this.Role = &role
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AgentMessage) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AgentMessage) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AgentMessage) SetRole(v string) {
	o.Role = &v
}

// GetContent returns the Content field value
func (o *AgentMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *AgentMessage) SetContent(v string) {
	o.Content = v
}

func (o AgentMessage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

type NullableAgentMessage struct {
	value *AgentMessage
	isSet bool
}

func (v NullableAgentMessage) Get() *AgentMessage {
	return v.value
}

func (v *NullableAgentMessage) Set(val *AgentMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentMessage(val *AgentMessage) *NullableAgentMessage {
	return &NullableAgentMessage{value: val, isSet: true}
}

func (v NullableAgentMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
