// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0
/*
Agent Manifest Definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package manifests

import (
	"encoding/json"
)

// checks if the AgentlessModelSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentlessModelSettings{}

// AgentlessModelSettings struct for AgentlessModelSettings
type AgentlessModelSettings struct {
	BaseUrl            *Str     `json:"base_url,omitempty"`
	ApiVersion         *Str     `json:"api_version,omitempty"`
	AzureEndpoint      *Str     `json:"azure_endpoint,omitempty"`
	AzureAdToken       *Str     `json:"azure_ad_token,omitempty"`
	Project            *Str     `json:"project,omitempty"`
	Organization       *Str     `json:"organization,omitempty"`
	RegionName         *Str     `json:"region_name,omitempty"`
	AwsAccessKeyId     *Str     `json:"aws_access_key_id,omitempty"`
	AwsSecretAccessKey *Str     `json:"aws_secret_access_key,omitempty"`
	AwsSessionToken    *Str     `json:"aws_session_token,omitempty"`
	AwsReadTimeout     *float32 `json:"aws_read_timeout,omitempty"`
	AwsConnectTimeout  *float32 `json:"aws_connect_timeout,omitempty"`
	ServiceAccountFile *Str     `json:"service_account_file,omitempty"`
	ProjectId          *Str     `json:"project_id,omitempty"`
	Region             *Str     `json:"region,omitempty"`
	ModelPublisher     *Str     `json:"model_publisher,omitempty"`
}

// NewAgentlessModelSettings instantiates a new AgentlessModelSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentlessModelSettings() *AgentlessModelSettings {
	this := AgentlessModelSettings{}
	return &this
}

// NewAgentlessModelSettingsWithDefaults instantiates a new AgentlessModelSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentlessModelSettingsWithDefaults() *AgentlessModelSettings {
	this := AgentlessModelSettings{}
	return &this
}

// GetBaseUrl returns the BaseUrl field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetBaseUrl() Str {
	if o == nil || IsNil(o.BaseUrl) {
		var ret Str
		return ret
	}
	return *o.BaseUrl
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetBaseUrlOk() (*Str, bool) {
	if o == nil || IsNil(o.BaseUrl) {
		return nil, false
	}
	return o.BaseUrl, true
}

// HasBaseUrl returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasBaseUrl() bool {
	if o != nil && !IsNil(o.BaseUrl) {
		return true
	}

	return false
}

// SetBaseUrl gets a reference to the given Str and assigns it to the BaseUrl field.
func (o *AgentlessModelSettings) SetBaseUrl(v Str) {
	o.BaseUrl = &v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetApiVersion() Str {
	if o == nil || IsNil(o.ApiVersion) {
		var ret Str
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetApiVersionOk() (*Str, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given Str and assigns it to the ApiVersion field.
func (o *AgentlessModelSettings) SetApiVersion(v Str) {
	o.ApiVersion = &v
}

// GetAzureEndpoint returns the AzureEndpoint field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetAzureEndpoint() Str {
	if o == nil || IsNil(o.AzureEndpoint) {
		var ret Str
		return ret
	}
	return *o.AzureEndpoint
}

// GetAzureEndpointOk returns a tuple with the AzureEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetAzureEndpointOk() (*Str, bool) {
	if o == nil || IsNil(o.AzureEndpoint) {
		return nil, false
	}
	return o.AzureEndpoint, true
}

// HasAzureEndpoint returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasAzureEndpoint() bool {
	if o != nil && !IsNil(o.AzureEndpoint) {
		return true
	}

	return false
}

// SetAzureEndpoint gets a reference to the given Str and assigns it to the AzureEndpoint field.
func (o *AgentlessModelSettings) SetAzureEndpoint(v Str) {
	o.AzureEndpoint = &v
}

// GetAzureAdToken returns the AzureAdToken field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetAzureAdToken() Str {
	if o == nil || IsNil(o.AzureAdToken) {
		var ret Str
		return ret
	}
	return *o.AzureAdToken
}

// GetAzureAdTokenOk returns a tuple with the AzureAdToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetAzureAdTokenOk() (*Str, bool) {
	if o == nil || IsNil(o.AzureAdToken) {
		return nil, false
	}
	return o.AzureAdToken, true
}

// HasAzureAdToken returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasAzureAdToken() bool {
	if o != nil && !IsNil(o.AzureAdToken) {
		return true
	}

	return false
}

// SetAzureAdToken gets a reference to the given Str and assigns it to the AzureAdToken field.
func (o *AgentlessModelSettings) SetAzureAdToken(v Str) {
	o.AzureAdToken = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetProject() Str {
	if o == nil || IsNil(o.Project) {
		var ret Str
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetProjectOk() (*Str, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given Str and assigns it to the Project field.
func (o *AgentlessModelSettings) SetProject(v Str) {
	o.Project = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetOrganization() Str {
	if o == nil || IsNil(o.Organization) {
		var ret Str
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetOrganizationOk() (*Str, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given Str and assigns it to the Organization field.
func (o *AgentlessModelSettings) SetOrganization(v Str) {
	o.Organization = &v
}

// GetRegionName returns the RegionName field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetRegionName() Str {
	if o == nil || IsNil(o.RegionName) {
		var ret Str
		return ret
	}
	return *o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetRegionNameOk() (*Str, bool) {
	if o == nil || IsNil(o.RegionName) {
		return nil, false
	}
	return o.RegionName, true
}

// HasRegionName returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasRegionName() bool {
	if o != nil && !IsNil(o.RegionName) {
		return true
	}

	return false
}

// SetRegionName gets a reference to the given Str and assigns it to the RegionName field.
func (o *AgentlessModelSettings) SetRegionName(v Str) {
	o.RegionName = &v
}

// GetAwsAccessKeyId returns the AwsAccessKeyId field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetAwsAccessKeyId() Str {
	if o == nil || IsNil(o.AwsAccessKeyId) {
		var ret Str
		return ret
	}
	return *o.AwsAccessKeyId
}

// GetAwsAccessKeyIdOk returns a tuple with the AwsAccessKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetAwsAccessKeyIdOk() (*Str, bool) {
	if o == nil || IsNil(o.AwsAccessKeyId) {
		return nil, false
	}
	return o.AwsAccessKeyId, true
}

// HasAwsAccessKeyId returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasAwsAccessKeyId() bool {
	if o != nil && !IsNil(o.AwsAccessKeyId) {
		return true
	}

	return false
}

// SetAwsAccessKeyId gets a reference to the given Str and assigns it to the AwsAccessKeyId field.
func (o *AgentlessModelSettings) SetAwsAccessKeyId(v Str) {
	o.AwsAccessKeyId = &v
}

// GetAwsSecretAccessKey returns the AwsSecretAccessKey field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetAwsSecretAccessKey() Str {
	if o == nil || IsNil(o.AwsSecretAccessKey) {
		var ret Str
		return ret
	}
	return *o.AwsSecretAccessKey
}

// GetAwsSecretAccessKeyOk returns a tuple with the AwsSecretAccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetAwsSecretAccessKeyOk() (*Str, bool) {
	if o == nil || IsNil(o.AwsSecretAccessKey) {
		return nil, false
	}
	return o.AwsSecretAccessKey, true
}

// HasAwsSecretAccessKey returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasAwsSecretAccessKey() bool {
	if o != nil && !IsNil(o.AwsSecretAccessKey) {
		return true
	}

	return false
}

// SetAwsSecretAccessKey gets a reference to the given Str and assigns it to the AwsSecretAccessKey field.
func (o *AgentlessModelSettings) SetAwsSecretAccessKey(v Str) {
	o.AwsSecretAccessKey = &v
}

// GetAwsSessionToken returns the AwsSessionToken field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetAwsSessionToken() Str {
	if o == nil || IsNil(o.AwsSessionToken) {
		var ret Str
		return ret
	}
	return *o.AwsSessionToken
}

// GetAwsSessionTokenOk returns a tuple with the AwsSessionToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetAwsSessionTokenOk() (*Str, bool) {
	if o == nil || IsNil(o.AwsSessionToken) {
		return nil, false
	}
	return o.AwsSessionToken, true
}

// HasAwsSessionToken returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasAwsSessionToken() bool {
	if o != nil && !IsNil(o.AwsSessionToken) {
		return true
	}

	return false
}

// SetAwsSessionToken gets a reference to the given Str and assigns it to the AwsSessionToken field.
func (o *AgentlessModelSettings) SetAwsSessionToken(v Str) {
	o.AwsSessionToken = &v
}

// GetAwsReadTimeout returns the AwsReadTimeout field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetAwsReadTimeout() float32 {
	if o == nil || IsNil(o.AwsReadTimeout) {
		var ret float32
		return ret
	}
	return *o.AwsReadTimeout
}

// GetAwsReadTimeoutOk returns a tuple with the AwsReadTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetAwsReadTimeoutOk() (*float32, bool) {
	if o == nil || IsNil(o.AwsReadTimeout) {
		return nil, false
	}
	return o.AwsReadTimeout, true
}

// HasAwsReadTimeout returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasAwsReadTimeout() bool {
	if o != nil && !IsNil(o.AwsReadTimeout) {
		return true
	}

	return false
}

// SetAwsReadTimeout gets a reference to the given float32 and assigns it to the AwsReadTimeout field.
func (o *AgentlessModelSettings) SetAwsReadTimeout(v float32) {
	o.AwsReadTimeout = &v
}

// GetAwsConnectTimeout returns the AwsConnectTimeout field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetAwsConnectTimeout() float32 {
	if o == nil || IsNil(o.AwsConnectTimeout) {
		var ret float32
		return ret
	}
	return *o.AwsConnectTimeout
}

// GetAwsConnectTimeoutOk returns a tuple with the AwsConnectTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetAwsConnectTimeoutOk() (*float32, bool) {
	if o == nil || IsNil(o.AwsConnectTimeout) {
		return nil, false
	}
	return o.AwsConnectTimeout, true
}

// HasAwsConnectTimeout returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasAwsConnectTimeout() bool {
	if o != nil && !IsNil(o.AwsConnectTimeout) {
		return true
	}

	return false
}

// SetAwsConnectTimeout gets a reference to the given float32 and assigns it to the AwsConnectTimeout field.
func (o *AgentlessModelSettings) SetAwsConnectTimeout(v float32) {
	o.AwsConnectTimeout = &v
}

// GetServiceAccountFile returns the ServiceAccountFile field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetServiceAccountFile() Str {
	if o == nil || IsNil(o.ServiceAccountFile) {
		var ret Str
		return ret
	}
	return *o.ServiceAccountFile
}

// GetServiceAccountFileOk returns a tuple with the ServiceAccountFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetServiceAccountFileOk() (*Str, bool) {
	if o == nil || IsNil(o.ServiceAccountFile) {
		return nil, false
	}
	return o.ServiceAccountFile, true
}

// HasServiceAccountFile returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasServiceAccountFile() bool {
	if o != nil && !IsNil(o.ServiceAccountFile) {
		return true
	}

	return false
}

// SetServiceAccountFile gets a reference to the given Str and assigns it to the ServiceAccountFile field.
func (o *AgentlessModelSettings) SetServiceAccountFile(v Str) {
	o.ServiceAccountFile = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetProjectId() Str {
	if o == nil || IsNil(o.ProjectId) {
		var ret Str
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetProjectIdOk() (*Str, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given Str and assigns it to the ProjectId field.
func (o *AgentlessModelSettings) SetProjectId(v Str) {
	o.ProjectId = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetRegion() Str {
	if o == nil || IsNil(o.Region) {
		var ret Str
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetRegionOk() (*Str, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given Str and assigns it to the Region field.
func (o *AgentlessModelSettings) SetRegion(v Str) {
	o.Region = &v
}

// GetModelPublisher returns the ModelPublisher field value if set, zero value otherwise.
func (o *AgentlessModelSettings) GetModelPublisher() Str {
	if o == nil || IsNil(o.ModelPublisher) {
		var ret Str
		return ret
	}
	return *o.ModelPublisher
}

// GetModelPublisherOk returns a tuple with the ModelPublisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentlessModelSettings) GetModelPublisherOk() (*Str, bool) {
	if o == nil || IsNil(o.ModelPublisher) {
		return nil, false
	}
	return o.ModelPublisher, true
}

// HasModelPublisher returns a boolean if a field has been set.
func (o *AgentlessModelSettings) HasModelPublisher() bool {
	if o != nil && !IsNil(o.ModelPublisher) {
		return true
	}

	return false
}

// SetModelPublisher gets a reference to the given Str and assigns it to the ModelPublisher field.
func (o *AgentlessModelSettings) SetModelPublisher(v Str) {
	o.ModelPublisher = &v
}

func (o AgentlessModelSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentlessModelSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BaseUrl) {
		toSerialize["base_url"] = o.BaseUrl
	}
	if !IsNil(o.ApiVersion) {
		toSerialize["api_version"] = o.ApiVersion
	}
	if !IsNil(o.AzureEndpoint) {
		toSerialize["azure_endpoint"] = o.AzureEndpoint
	}
	if !IsNil(o.AzureAdToken) {
		toSerialize["azure_ad_token"] = o.AzureAdToken
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.RegionName) {
		toSerialize["region_name"] = o.RegionName
	}
	if !IsNil(o.AwsAccessKeyId) {
		toSerialize["aws_access_key_id"] = o.AwsAccessKeyId
	}
	if !IsNil(o.AwsSecretAccessKey) {
		toSerialize["aws_secret_access_key"] = o.AwsSecretAccessKey
	}
	if !IsNil(o.AwsSessionToken) {
		toSerialize["aws_session_token"] = o.AwsSessionToken
	}
	if !IsNil(o.AwsReadTimeout) {
		toSerialize["aws_read_timeout"] = o.AwsReadTimeout
	}
	if !IsNil(o.AwsConnectTimeout) {
		toSerialize["aws_connect_timeout"] = o.AwsConnectTimeout
	}
	if !IsNil(o.ServiceAccountFile) {
		toSerialize["service_account_file"] = o.ServiceAccountFile
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.ModelPublisher) {
		toSerialize["model_publisher"] = o.ModelPublisher
	}
	return toSerialize, nil
}

type NullableAgentlessModelSettings struct {
	value *AgentlessModelSettings
	isSet bool
}

func (v NullableAgentlessModelSettings) Get() *AgentlessModelSettings {
	return v.value
}

func (v *NullableAgentlessModelSettings) Set(val *AgentlessModelSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentlessModelSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentlessModelSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentlessModelSettings(val *AgentlessModelSettings) *NullableAgentlessModelSettings {
	return &NullableAgentlessModelSettings{value: val, isSet: true}
}

func (v NullableAgentlessModelSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentlessModelSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
