builds:
  - main: ./cmd/main.go
    binary: wfsm
    env:
      - CGO_ENABLED=1
    ldflags: "-s -w {{ .Env.GORELEASER_LDFLAGS }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "wfsm{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "acpilot_checksums.txt"

changelog:
  skip: true

nfpms:
  - vendor: Outshift by Cisco
    maintainer: Outshift <outshift@cisco.com>
    homepage: https://cisco.com/
    description: Command-line interface for Agent Workflow Server
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    license: Apache 2.0
