# templates/secret.yaml
{{- range .Values.agents }}
{{- if not .existingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
type: Opaque
data:
  {{- range .secretEnvs }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
