---
name: dependency

on:
  # Review dependencies on pull requests to the default branch
  pull_request:
    branches: ["main"]

# Declare default permissions as read-only
permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: 🔂 dependency review
        uses: actions/dependency-review-action@38ecb5b593bf0eb19e335c03f97670f792489a8b # v4.7.0
        with:
          fail-on-severity: "high"
          deny-licenses: "AGPL-1.0, AGPL-3.0"
          comment-summary-in-pr: true
          warn-on-openssf-scorecard-level: 3
