name: Dev release

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
jobs:
  release-dev:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: goreleaser/goreleaser-cross:v1.24.1

    env:
      GO_VERSION: 1.23.4
      GOFLAGS: -mod=readonly
      GO111MODULE: "on"
      CGO_ENABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}


      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd wfsm
          git config --global --add safe.directory '*'
          make release
