name: Dev release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.23.4
      GOFLAGS: -mod=readonly

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Build
        run: |
          cd wfsm
          make build

      - name: Run tests
        run: |
          cd wfsm
          make test

  release-dev:
    name: Dev release
    runs-on: ubuntu-latest
    needs: build

    env:
      GO_VERSION: 1.23.4
      GOFLAGS: -mod=readonly
      GO111MODULE: "on"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Update package registry
        run: sudo apt update --yes

      - name: Install RPM
        run: sudo apt install rpm --yes

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd wfsm
          make release-dev
